### PR TITLE
feat: split big image in small #45

### PR DESCRIPTION
**Pull request by strdr4605**
Screenshot 2022-02-26 at 17 42 11

### CODE REVIEW

**Comment by johnsmithm** [comment]
poti crea o functio in scr/utils.py?

**Comment by johnsmithm** [comment]
adauga si un  y_padding si x_padding parameters

**Comment by octavflorescu** [comment]
1. If we use this splitting technique, maybe some big images will not divide evenly by the desired bbox, so some images will not have the target size.
e.g. cropping1 (first) image.
cropping1
This should not be a problem when predicting, if we are aware of it, and reshape the crop-image using zero padding-reshape.
An alternative would be to change the code to always output crops of the desired shape, by automatically filling in the missing pixels with zeros. i recommend this approach, but it is an open discussion 😄

2. Sorry for not being in the discussion meeting, maybe this step will be included in another commit, but here it is my feedback:
For "join the prediction into one" i assume it is more relevant if we join the prediction boxes into one, not only recomposing the initial/source image by joining the pre-rendered images with bboxes drawn onto them. This especially once we consider the overlap (=padding).
In the **overlapping area**, i guess bboxes should be iou-matched while keeping the bbox only in the cropped image which contains most of the tree (greedy: biggest iou). (iou == intersection over union)
e.g. cropping2 (second) image attached.
cropping2
per exemple, considering D1's bbox as Ground Truth, when "joining the predictions into one", both crop0 and crop1 (with their paddings) will see the same tree, but crop1 would see most/all of the tree. So there we should keep (in the joined predictions) only the bbox predicted by crop1.

**Comment by johnsmithm** [comment]
solved in #62

**Pull request closed without merging**
